### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by blackpintz** [blackpintz/tic-tac-game-js#2]

**Comment by mariosknl** [comment]
Great project Rose. Well done

**Comment by kubilaycaglayan** [comment]
```css
.class-name {
  transform: scale(1.1);
}
```

:bulb: So it is not a **transition** but transform.

Thanks for the presentation, Rose! :blush:
